services:
  jobmanager:
    image: flink:1.17-java11
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - realtimeanalytics    

  taskmanager:
    image: flink:1.17-java11
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    networks:
      - realtimeanalytics    

  flinksql:
    image: flink:1.17-java11
    container_name: flink-sql-client
    depends_on:
      - jobmanager
    entrypoint: ["flink", "sql-client", "embedded"]
    networks:
      - realtimeanalytics    

  flink-processing-service:
    build: flink-processing-service
    container_name: flink-processing-service
    depends_on:
      - jobmanager
      - taskmanager
    environment:
      - FLINK_JOBMANAGER_HOST=jobmanager
      - FLINK_JOBMANAGER_PORT=6123
      - FLINK_PARALLELISM=2
    networks:
      - realtimeanalytics    

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: rides_db
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - realtimeanalytics    
volumes:
  pgdata: 

networks:
  realtimeanalytics:
    name: realtimeanalytics  